/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.distributed.proto;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ClientDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClientDetails\",\"namespace\":\"avro.distributed.proto\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"ClientType\",\"symbols\":[\"USER\",\"FRIDGE\",\"LIGHT\",\"SENSOR\"]}},{\"name\":\"status\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public avro.distributed.proto.ClientType type;
  @Deprecated public boolean status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ClientDetails() {}

  /**
   * All-args constructor.
   */
  public ClientDetails(java.lang.CharSequence name, avro.distributed.proto.ClientType type, java.lang.Boolean status) {
    this.name = name;
    this.type = type;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return type;
    case 2: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: type = (avro.distributed.proto.ClientType)value$; break;
    case 2: status = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'type' field.
   */
  public avro.distributed.proto.ClientType getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(avro.distributed.proto.ClientType value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'status' field.
   */
  public java.lang.Boolean getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.Boolean value) {
    this.status = value;
  }

  /** Creates a new ClientDetails RecordBuilder */
  public static avro.distributed.proto.ClientDetails.Builder newBuilder() {
    return new avro.distributed.proto.ClientDetails.Builder();
  }
  
  /** Creates a new ClientDetails RecordBuilder by copying an existing Builder */
  public static avro.distributed.proto.ClientDetails.Builder newBuilder(avro.distributed.proto.ClientDetails.Builder other) {
    return new avro.distributed.proto.ClientDetails.Builder(other);
  }
  
  /** Creates a new ClientDetails RecordBuilder by copying an existing ClientDetails instance */
  public static avro.distributed.proto.ClientDetails.Builder newBuilder(avro.distributed.proto.ClientDetails other) {
    return new avro.distributed.proto.ClientDetails.Builder(other);
  }
  
  /**
   * RecordBuilder for ClientDetails instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClientDetails>
    implements org.apache.avro.data.RecordBuilder<ClientDetails> {

    private java.lang.CharSequence name;
    private avro.distributed.proto.ClientType type;
    private boolean status;

    /** Creates a new Builder */
    private Builder() {
      super(avro.distributed.proto.ClientDetails.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.distributed.proto.ClientDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ClientDetails instance */
    private Builder(avro.distributed.proto.ClientDetails other) {
            super(avro.distributed.proto.ClientDetails.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public avro.distributed.proto.ClientDetails.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public avro.distributed.proto.ClientDetails.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'type' field */
    public avro.distributed.proto.ClientType getType() {
      return type;
    }
    
    /** Sets the value of the 'type' field */
    public avro.distributed.proto.ClientDetails.Builder setType(avro.distributed.proto.ClientType value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'type' field has been set */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'type' field */
    public avro.distributed.proto.ClientDetails.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'status' field */
    public java.lang.Boolean getStatus() {
      return status;
    }
    
    /** Sets the value of the 'status' field */
    public avro.distributed.proto.ClientDetails.Builder setStatus(boolean value) {
      validate(fields()[2], value);
      this.status = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'status' field has been set */
    public boolean hasStatus() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'status' field */
    public avro.distributed.proto.ClientDetails.Builder clearStatus() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public ClientDetails build() {
      try {
        ClientDetails record = new ClientDetails();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (avro.distributed.proto.ClientType) defaultValue(fields()[1]);
        record.status = fieldSetFlags()[2] ? this.status : (java.lang.Boolean) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
