/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.distributed.proto;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ClientType { 
  USER, FRIDGE, LIGHT, SENSOR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ClientType\",\"namespace\":\"avro.distributed.proto\",\"symbols\":[\"USER\",\"FRIDGE\",\"LIGHT\",\"SENSOR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
