/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.distributed.proto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface LightProto {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"LightProto\",\"namespace\":\"avro.distributed.proto\",\"types\":[],\"messages\":{\"set_light\":{\"request\":[{\"name\":\"light_state\",\"type\":\"boolean\"}],\"response\":\"null\",\"one-way\":true}}}");
  void set_light(boolean light_state);

  @SuppressWarnings("all")
  public interface Callback extends LightProto {
    public static final org.apache.avro.Protocol PROTOCOL = avro.distributed.proto.LightProto.PROTOCOL;
  }
}