/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.distributed.proto;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SensorInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SensorInfo\",\"namespace\":\"avro.distributed.proto\",\"fields\":[{\"name\":\"client_info\",\"type\":{\"type\":\"record\",\"name\":\"ClientInfo\",\"fields\":[{\"name\":\"ip\",\"type\":\"string\"},{\"name\":\"port\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"ClientType\",\"symbols\":[\"USER\",\"FRIDGE\",\"LIGHT\",\"SENSOR\"]}},{\"name\":\"key\",\"type\":\"int\"},{\"name\":\"online\",\"type\":\"boolean\"}]}},{\"name\":\"temperature_list\",\"type\":{\"type\":\"array\",\"items\":\"float\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public avro.distributed.proto.ClientInfo client_info;
  @Deprecated public java.util.List<java.lang.Float> temperature_list;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public SensorInfo() {}

  /**
   * All-args constructor.
   */
  public SensorInfo(avro.distributed.proto.ClientInfo client_info, java.util.List<java.lang.Float> temperature_list) {
    this.client_info = client_info;
    this.temperature_list = temperature_list;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return client_info;
    case 1: return temperature_list;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: client_info = (avro.distributed.proto.ClientInfo)value$; break;
    case 1: temperature_list = (java.util.List<java.lang.Float>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'client_info' field.
   */
  public avro.distributed.proto.ClientInfo getClientInfo() {
    return client_info;
  }

  /**
   * Sets the value of the 'client_info' field.
   * @param value the value to set.
   */
  public void setClientInfo(avro.distributed.proto.ClientInfo value) {
    this.client_info = value;
  }

  /**
   * Gets the value of the 'temperature_list' field.
   */
  public java.util.List<java.lang.Float> getTemperatureList() {
    return temperature_list;
  }

  /**
   * Sets the value of the 'temperature_list' field.
   * @param value the value to set.
   */
  public void setTemperatureList(java.util.List<java.lang.Float> value) {
    this.temperature_list = value;
  }

  /** Creates a new SensorInfo RecordBuilder */
  public static avro.distributed.proto.SensorInfo.Builder newBuilder() {
    return new avro.distributed.proto.SensorInfo.Builder();
  }
  
  /** Creates a new SensorInfo RecordBuilder by copying an existing Builder */
  public static avro.distributed.proto.SensorInfo.Builder newBuilder(avro.distributed.proto.SensorInfo.Builder other) {
    return new avro.distributed.proto.SensorInfo.Builder(other);
  }
  
  /** Creates a new SensorInfo RecordBuilder by copying an existing SensorInfo instance */
  public static avro.distributed.proto.SensorInfo.Builder newBuilder(avro.distributed.proto.SensorInfo other) {
    return new avro.distributed.proto.SensorInfo.Builder(other);
  }
  
  /**
   * RecordBuilder for SensorInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SensorInfo>
    implements org.apache.avro.data.RecordBuilder<SensorInfo> {

    private avro.distributed.proto.ClientInfo client_info;
    private java.util.List<java.lang.Float> temperature_list;

    /** Creates a new Builder */
    private Builder() {
      super(avro.distributed.proto.SensorInfo.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.distributed.proto.SensorInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.client_info)) {
        this.client_info = data().deepCopy(fields()[0].schema(), other.client_info);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.temperature_list)) {
        this.temperature_list = data().deepCopy(fields()[1].schema(), other.temperature_list);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing SensorInfo instance */
    private Builder(avro.distributed.proto.SensorInfo other) {
            super(avro.distributed.proto.SensorInfo.SCHEMA$);
      if (isValidValue(fields()[0], other.client_info)) {
        this.client_info = data().deepCopy(fields()[0].schema(), other.client_info);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.temperature_list)) {
        this.temperature_list = data().deepCopy(fields()[1].schema(), other.temperature_list);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'client_info' field */
    public avro.distributed.proto.ClientInfo getClientInfo() {
      return client_info;
    }
    
    /** Sets the value of the 'client_info' field */
    public avro.distributed.proto.SensorInfo.Builder setClientInfo(avro.distributed.proto.ClientInfo value) {
      validate(fields()[0], value);
      this.client_info = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'client_info' field has been set */
    public boolean hasClientInfo() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'client_info' field */
    public avro.distributed.proto.SensorInfo.Builder clearClientInfo() {
      client_info = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'temperature_list' field */
    public java.util.List<java.lang.Float> getTemperatureList() {
      return temperature_list;
    }
    
    /** Sets the value of the 'temperature_list' field */
    public avro.distributed.proto.SensorInfo.Builder setTemperatureList(java.util.List<java.lang.Float> value) {
      validate(fields()[1], value);
      this.temperature_list = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'temperature_list' field has been set */
    public boolean hasTemperatureList() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'temperature_list' field */
    public avro.distributed.proto.SensorInfo.Builder clearTemperatureList() {
      temperature_list = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public SensorInfo build() {
      try {
        SensorInfo record = new SensorInfo();
        record.client_info = fieldSetFlags()[0] ? this.client_info : (avro.distributed.proto.ClientInfo) defaultValue(fields()[0]);
        record.temperature_list = fieldSetFlags()[1] ? this.temperature_list : (java.util.List<java.lang.Float>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
