/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.distributed.proto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface UserProto {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"UserProto\",\"namespace\":\"avro.distributed.proto\",\"types\":[],\"messages\":{\"is_alive\":{\"request\":[],\"response\":\"null\"}}}");
  java.lang.Void is_alive() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends UserProto {
    public static final org.apache.avro.Protocol PROTOCOL = avro.distributed.proto.UserProto.PROTOCOL;
    void is_alive(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}